version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile_dev
    command: sleep infinity
    ports:
      - 8080:8080
    environment:
      LANG: C.UTF-8
      SERVER_NAME: ${SERVER_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./app:/app"
    depends_on:
      - mysql
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.MySQL
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: "Asia/Tokyo"
    volumes:
      - ./local-db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.10.2
    command: /bin/sh -c "envsubst '$$SSL_CERTIFICATE_PATH $$SSL_CERTIFICATE_KEY_PATH $$SERVER_NAME $$APP_CONTAINER_NAME'< /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
      SERVER_NAME: ${SERVER_NAME}
      APP_CONTAINER_NAME: ${APP_CONTAINER_NAME}
      SSL_CERTIFICATE_PATH: ${SSL_CERTIFICATE_PATH}
      SSL_CERTIFICATE_KEY_PATH: ${SSL_CERTIFICATE_KEY_PATH}

    volumes:
      - "./local-ssl:/etc/mkcert/certificates"
      - "./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template"
    depends_on:
      - app
